<?php


/*
 * DB connection script for Editor
 * Automatically generated by http://editor.datatables.net/generator
 */

error_reporting(E_ALL);
ini_set('display_errors', '1');

/*
 * Edit the following with your database connection options
 */
/*$sql_details = array(
	"type" => "Mysql",
	"user" => DB_USER,
	"pass" => DB_PASSWORD,
	"host" => DB_SERVER,
	"port" => "3306",
	"db"   => DB_NAME
);*/
$sql_details = array(
	"type" => "Mysql",
	"user" => "asterisk",
	"pass" => "s266Q48OG488g4I",
	"host" => "localhost",
	"port" => "3306",
	"db"   => "asterisk"
);

